version: '3.8'

services:
  # ============================================================================
  # Backend API (FastAPI)
  # ============================================================================
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dom360-backend
    environment:
      # Database - PostgreSQL na VPS
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-dom360_db_sdk}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      
      # Backend Settings
      BACKEND_PORT: 3001
      BACKEND_BIND_HOST: 0.0.0.0
      BACKEND_BIND_PORT: 3001
      PUBLIC_BACKEND_URL: ${PUBLIC_BACKEND_URL:-http://backend:3001}
      
      # Frontend Settings
      PUBLIC_FRONTEND_URL: ${PUBLIC_FRONTEND_URL:-http://frontend:5173}
      
      # API & Security
      AGENT_API_URL: ${AGENT_API_URL:-http://localhost:8000}
      JWT_SECRET: ${JWT_SECRET:-eSGm2XZ8lBfB++3TOt0Tp0rR8MimWnohTD9oqaq+Q84=}
      
      # CORS
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:5173,http://localhost:3001,http://frontend:5173,http://backend:3001}
      
      # Environment
      PYTHON_ENV: ${PYTHON_ENV:-production}
      NODE_ENV: ${NODE_ENV:-production}
    
    ports:
      - "3001:3001"
    
    networks:
      - dom360-network
    
    volumes:
      - ./logs:/app/logs
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped

  # ============================================================================
  # Frontend (React + Vite)
  # ============================================================================
  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    container_name: dom360-frontend
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3001}
    
    ports:
      - "5173:5173"
    
    networks:
      - dom360-network
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    restart: unless-stopped

# ============================================================================
# Rede Docker
# ============================================================================
networks:
  dom360-network:
    driver: bridge
