version: '3.8'

services:
  # ============================================================================
  # Backend API (FastAPI)
  # ============================================================================
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: dom360-backend:latest
    container_name: dom360-backend
    environment:
      # Database - PostgreSQL na VPS
      DB_HOST: ${DB_HOST:-host.docker.internal}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-dom_db_360}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      
      # Backend Settings
      BACKEND_PORT: 3001
      BACKEND_BIND_HOST: 0.0.0.0
      BACKEND_BIND_PORT: 3001
      PUBLIC_BACKEND_URL: ${PUBLIC_BACKEND_URL:-https://api.srcjohann.com.br}
      
      # Frontend Settings
      PUBLIC_FRONTEND_URL: ${PUBLIC_FRONTEND_URL:-https://sdk.srcjohann.com.br}
      
      # API & Security
      AGENT_API_URL: ${AGENT_API_URL:-http://localhost:8000}
      JWT_SECRET: ${JWT_SECRET:-eSGm2XZ8lBfB++3TOt0Tp0rR8MimWnohTD9oqaq+Q84=}
      
      # CORS
      CORS_ORIGINS: ${CORS_ORIGINS:-https://sdk.srcjohann.com.br,https://api.srcjohann.com.br}
      
      # Environment
      PYTHON_ENV: ${PYTHON_ENV:-production}
      NODE_ENV: ${NODE_ENV:-production}
    
    networks:
      - sdk-network
    
    volumes:
      - ./logs:/app/logs
    
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    labels:
      # Traefik - Roteamento para api.srcjohann.com.br
      - "traefik.enable=true"
      - "traefik.http.routers.dom360-backend.rule=Host(`api.srcjohann.com.br`)"
      - "traefik.http.routers.dom360-backend.entrypoints=websecure"
      - "traefik.http.routers.dom360-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.dom360-backend.loadbalancer.server.port=3001"
      # CORS headers
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworigins=https://sdk.srcjohann.com.br"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,PATCH,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=3600"
      - "traefik.http.routers.dom360-backend.middlewares=cors"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s

  # ============================================================================
  # Frontend (React + Vite)
  # ============================================================================
  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    image: dom360-frontend:latest
    container_name: dom360-frontend
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      VITE_API_URL: ${VITE_API_URL:-https://api.srcjohann.com.br}
    
    networks:
      - sdk-network
    
    labels:
      # Traefik - Roteamento para sdk.srcjohann.com.br
      - "traefik.enable=true"
      - "traefik.http.routers.dom360-frontend.rule=Host(`sdk.srcjohann.com.br`)"
      - "traefik.http.routers.dom360-frontend.entrypoints=websecure"
      - "traefik.http.routers.dom360-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.dom360-frontend.loadbalancer.server.port=5173"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    restart: unless-stopped
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s

# ============================================================================
# Rede Docker para conectar os serviços
# ============================================================================
networks:
  sdk-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
